name: cd

#on:
#  push:
#    branches:
#      - main

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Release in Production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PASSPHRASE }}
        fingerprint: ${{ secrets.FINGERPRINT }}
        script_stop: true
        script: |
          cd /var/www/bus/
          git pull
          npm ci
          npm run build
