name: ci

on: push

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.after }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: mkdir -p dist && cp -f examples/.env.json dist/.env.json && npm run build --if-present
      - name: Test
        run: npm test
